apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    group: db
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
    - protocol: TCP
      nodePort: 30004
      port: 80          # port exposed outside ClusterIP
      targetPort: 80