apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app: pgadmin
    group: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
        type: db
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "ivan.aukhim@gmail.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "admin"
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"