apiVersion: v1
kind: Service
metadata:
  name: db-postgres
  labels:
    group: db
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      nodePort: 30002
      port: 5432          # port exposed outside ClusterIP
      targetPort: 5432