apiVersion: v1
kind: Service
metadata:
  name: rent-app
  labels:
    group: rent-app
spec:
  type: NodePort
  selector:             # indicates into which pods ClusterIP provides access
    app: rent-app
  ports:
    - protocol: TCP
      nodePort: 30003
      port: 8080          # port exposed outside ClusterIP
      targetPort: 8080