apiVersion: apps/v1
kind: Deployment
metadata:
  name: rent-app
  labels:
    app: rent-app
    group: rent-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rent-app    # indicates which Pods (with which labeles) need be handled by this Deployment
  template:
    metadata:         # indicates the metadata that will be added to each Pod
      labels:
        app: rent-app
        group: rent-app
    spec:
      containers:     # defines a running container inside the Pod
        - name: rent-app
          image: iaukhim/rent-app:latest
          volumeMounts:
            - mountPath: /certificates
              name: certificates-volume
            - mountPath: root/.ssh
              name: gitkey
          ports:
            - containerPort: 8080   # which port of the container is exposed to the Pod
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: certificates-volume
          hostPath:
            # directory location on host
            path: /certificates
        - name: gitkey
          hostPath:
            path: /home/newbie/.ssh